multidisabler: Patch R/O F2FS Vendor Image

diff --git a/recovery/root/system/bin/multidisabler b/recovery/root/system/bin/multidisabler
--- a/recovery/root/system/bin/multidisabler
+++ b/recovery/root/system/bin/multidisabler
@@ -4,160 +4,49 @@
 #
 # Use this to prime your device after installing TWRP.
 
+ram=/ramfs
+vendor_image=${ram}/vendor.img
+
 md5() {
-  md5sum -b "$1"
+  md5sum -b "$1" | cut -d' ' -f1
 }
 
-file_changed() {
-  local file="$1"
-  local old_md5="$2"
-  local new_md5=$( md5 "$file" )
-
-  if [ $new_md5 != $old_md5 ]; then
-    echo " -     ...modified."
-  else
-    echo " -     ...unchanged."
-  fi
-}
-
-resize_vendor() {
-  local dm_block_ext4=$(df -t ext4 | grep "/vendor" | cut -DF1)
-  local dm_block_f2fs=$(df -t f2fs | grep "/vendor" | cut -DF1)
-
-  if [ "$dm_block_ext4" ]; then
-    echo " - Unmounting /vendor..."
-    umount /vendor
-    echo " - Checking vendor block partition before resizing..."
-    e2fsck -f $dm_block_ext4
-    echo " - Resizing the filesystem on $dm_block_ext4..."
-    resize2fs $dm_block_ext4
-    echo " - Make the partition R/W by unsharing its blocks..."
-    e2fsck -E unshare_blocks $dm_block_ext4
-  elif [ "$dm_block_f2fs" ]; then
-    vendor_size_mb=$(du -sm /vendor | cut -f1)
-    new_vendor_size_mb=`echo $vendor_size_mb \* 1.7 |bc`
-    new_vendor_size_mb=${new_vendor_size_mb%.*}
-    uuid=$(toybox blkid $dm_block_f2fs | egrep '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}' -o)
-    echo " - Create R/W vendor image..."
-    truncate -s ${new_vendor_size_mb}M /tmp/vendor-rw.img
-    make_f2fs -g android -O project_quota,extra_attr,inode_checksum,sb_checksum,compression,flexible_inline_xattr,verity,inode_crtime -U $uuid -f -l vendor /tmp/vendor-rw.img
-    mkdir -p /tmp/vendor-rw
-    mount /tmp/vendor-rw.img /tmp/vendor-rw
-    echo " - Copy old R/O vendor file to our new created..."
-    cp -a --preserve=all /vendor/* /tmp/vendor-rw
-    echo " - Restoring SELinux contexts to our new R/W vendor..."
-    busybox chcon -h -R --reference=/vendor /tmp/vendor-rw
-    umount /vendor
-    umount /tmp/vendor-rw
-    echo " - Checking vendor image before flashing..."
-    fsck.f2fs -f /tmp/vendor-rw.img
-    echo " - Dynamic partition resizing using lptools"
-    lptools resize vendor $(wc -c < /tmp/vendor-rw.img)
-    lptools unmap vendor
-    lptools map vendor
-    echo " - Write our new R/W vendor image, Please wait..."
-    dd if=/tmp/vendor-rw.img of=/dev/block/bootdevice/by-name/vendor
-    rm -rf /tmp/vendor-rw*
-  fi
-  echo " - Remounting /vendor..."
-  mount /vendor
-  mount -o remount,rw /vendor
-}
-
-vendor_free_size_check() {
-  if dd if=/dev/zero of=/vendor/test bs=1 count=1 2>/dev/null; then
-    # echo " -     ...succeeded."
-    rm -f /vendor/test
-  else
-    echo " - Checking vendor free size..."
-    echo " -     ...No free space left on vendor, attempting to resize vendor..."
-    echo " "
-    rm -f /vendor/test
-    resize_vendor
-  fi
-}
-
-disable_fbe() {
-  local md5
-  local i
-  fstab_files=`grep -lr 'fileencryption' vendor/etc`
-
-  #
-  # Exynos devices = fstab.exynos*.
-  # MediaTek devices = fstab.mt*.
-  # Snapdragon devices = fstab.qcom, fstab.emmc, fstab.default
-  #
-  for i in $fstab_files; do
-    if [ -f $i ]; then
-      echo " - Disabling file-based encryption (FBE) for /data..."
-      echo " -   Found $i."
-      md5=$( md5 $i )
-      # This comments out the offending line and adds an edited one.
-      sed -i -e 's/^\([^#].*\)fileencryption=[^,]*\(.*\)$/# &\n\1encryptable\2/g' $i
-      file_changed $i $md5
+disable_encryption() {
+    echo "- Disabling encryption..."
+    chksum=$(md5 "$vendor_image")
+    # Target: /vendor/etc/fstab.*
+    gnused -i -b 's|fileencryption=|notencryptable=|g' $vendor_image
+    nchksum=$(md5 "$vendor_image")
+    if [ "$chksum" != "$nchksum" ]; then
+        echo " -    Success..."
+    else
+        echo " -    Already disabled..."
     fi
-  done
-}
-
-disable_fde() {
-  local md5
-  local i
-  fstab_files=`grep -lr 'forceencrypt' vendor/etc`
-
-  #
-  # Exynos devices = fstab.exynos*.
-  # MediaTek devices = fstab.mt*.
-  # Snapdragon devices = fstab.qcom, fstab.emmc, fstab.default
-  #
-  for i in $fstab_files; do
-    if [ -f $i ]; then
-      echo " - Disabling full-disk encryption (FDE) for /data..."
-      echo " -   Found $i."
-      md5=$( md5 $i )
-      # This comments out the offending line and adds an edited one.
-      sed -i -e 's/^\([^#].*\)forceencrypt=[^,]*\(.*\)$/# &\n\1encryptable\2/g' $i
-      file_changed $i $md5
-    fi
-  done
 }
 
 disable_recovery_restoration() {
-  local r=recovery-from-boot.p
-  local found
-  local i
-
-  echo " - Disabling restoration of stock recovery..."
-
-  for i in $ANDROID_ROOT $ANDROID_ROOT/system /vendor; do
-    if [ -f $i/$r~ ]; then
-	echo " -   ...already disabled."
-	found=true
-	break
+    echo "- Disabling recovery restoration..."
+    chksum=$(md5 "$vendor_image")
+    # Target: /vendor/bin/install-recovery.sh (is the script that does the restoration, so we edit it.)
+    gnused -i -b 's|/vendor/recovery-from-boot.p|/vendor/recovery-from-bsod.p|g' $vendor_image
+    nchksum=$(md5 "$vendor_image")
+    if [ "$chksum" != "$nchksum" ]; then
+        echo " -    Success..."
+    else
+        echo " -    Already disabled..."
     fi
+}
 
-    if [ -f $i/$r ]; then
-      echo " -   Found $i/$r. Disabling..."
-      mv $i/$r $i/$r~
-
-      if [ -f $i/$r~ ]; then
-	echo " -     ...succeeded."
-      else
-	echo " -     ...failed."
-      fi
-
-      found=true
-      break
+fsck() {
+    fsck.f2fs -f -y $vendor_image
+    if [ "$?" != "0" ]; then
+        echo " - ERROR: Failed to run fsck!!! (Unexpected behavior)"
     fi
-
-  done
-
-  [ -z "$found" ] && echo " -   Found no stock recovery. Pfft."
 }
 
 echo " "
 echo "Multi-disabler for Samsung devices"
-echo "running Android 9 or later."
-echo "by Ian Macdonald, enhanced by afaneh92"
+echo "running ReadOnly F2FS Vendor Images."
 echo " "
 
 os=$(getprop ro.build.version.release)
@@ -195,38 +84,56 @@ echo " - Detected a $device device with a $fw bootloader."
 echo " - The environment appears to be Android $major."
 echo " "
 
-echo " - Mounting $ANDROID_ROOT..."
-mount $ANDROID_ROOT 2>/dev/null
-mount -o remount,rw $ANDROID_ROOT 2>/dev/null
-
-if ! mount | grep $ANDROID_ROOT >/dev/null; then
-  ANDROID_ROOT=/system_root
-  echo " -   Attempt failed. Mounting at $ANDROID_ROOT..."
-  mount -o rw $ANDROID_ROOT
-  if ! mount | grep $ANDROID_ROOT >/dev/null; then
-    echo " -   Even that attempt failed. Aborting..."
-    exit 2
-  fi
-fi
-
 echo " - Mounting /vendor..."
-mount /vendor
-mount -o remount,rw /vendor
-
-if ! mount | grep /vendor >/dev/null; then
+mount -o ro /vendor &>/dev/null
+if ! mount | grep -q /vendor; then
   echo " -   Mount failed. Aborting..."
-  exit 3
+  exit 1
 fi
 
-vendor_free_size_check
-disable_fbe
-disable_fde
-disable_recovery_restoration
+dm_block=$(df -t f2fs | grep "/vendor" | cut -DF1)
+if [ "$dm_block" == "" ]; then
+    echo " - ERROR: Could not determine vendor block..."
+    exit 1
+fi
+echo " - Detected vendor at ${dm_block}"
 
-echo " - Unmounting /vendor..."
-umount /vendor
-echo " - Unmounting $ANDROID_ROOT..."
-umount $ANDROID_ROOT
+umount /vendor &>/dev/null
+if mount | grep -q /vendor; then
+  echo " -   Unmount failed. Aborting..."
+  exit 1
+fi
+
+# /tmp has only half ram, so we mount another tmpfs
+if mount | grep -q ${ram}; then
+    umount ${ram} &>/dev/null
+fi
+mkdir -p ${ram}
+mount -t tmpfs -o size=$(free -b | awk 'NR==2{print $2}') none ${ram}
+if ! mount | grep -q ${ram}; then
+    echo " - Couldn't mount RAMFS for storing vendor..."
+    exit 1
+fi
+
+echo " - Copying vendor to RAM..."
+dd if=$dm_block of=$vendor_image bs=2097152
+if [ "$?" != "0" ]; then
+    echo "-    Failed..."
+    exit 1
+fi
+echo "-    Done..."
+
+shrink "$vendor_image"
+
+disable_encryption
+disable_recovery_restoration
+fsck
+
+echo " - Flashing vendor..."
+dd if=$vendor_image of=$dm_block bs=2097152
+echo " - Cleaning..."
+rm -f $vendor_image
+umount ${ram} &>/dev/null
 
 echo " "
 echo " - Finished."
