multidisabler: Only run on f2fs images
Change-Id: I7d23e8d89054f19bb2846d6ec48b26039e435bbd
Signed-off-by: Gabriel2392 <gabriel824m@gmail.com>

diff --git a/recovery/root/system/bin/multidisabler b/recovery/root/system/bin/multidisabler
--- a/recovery/root/system/bin/multidisabler
+++ b/recovery/root/system/bin/multidisabler
@@ -104,6 +104,13 @@ lptools unmap vendor
 lptools map vendor
 mount_vendor "${dm_block}" "/tmp/vendor" || exit 1
 
+if ! mount | grep "/tmp/vendor" | grep -qs "f2fs"; then
+  echo " - Vendor isn't f2fs, abort..."
+  umount_vendor "/tmp/vendor" || exit 0
+  rm -rf "/tmp/vendor"
+  exit 0
+fi
+
 if [ ! -e "${dm_block}" ]; then
   echo " - Error: Could not determine vendor block..."
   exit 1
